export const agents = [
  {
    code: "B-01",
    slug: "tabiq",
    name: "طَبِّق",
    nameEn: "TABBIQ",
    category: "الامتثال والعمليات المالية",
    categoryEn: "Compliance & Finance Operations",
    role: "وكيل الفوترة الإلكترونية وتكامل ZATCA",
    roleEn: "ZATCA e-invoicing and finance workflow agent",
    quote: "هات الفاتورة... والباقي عليّ.",
    quoteEn: "Hand me the invoice. I will keep the workflow moving.",
    scenario:
      "عندما تتكدس الفواتير وتصبح الحقول وملفات XML وحالات الإرسال عملاً يومياً مرهقاً، يدخل طَبِّق ليرتب المسار قبل أن تتحول التفاصيل الصغيرة إلى تأخير كبير.",
    scenarioEn:
      "When invoices, XML fields and submission statuses become a daily operational burden, TABBIQ organizes the workflow before small details turn into expensive delays.",
    tasks: [
      "استخراج بيانات الفاتورة والتحقق من اكتمال الحقول المطلوبة",
      "تجهيز UUID وXML ومسار التكامل بحسب النظام المعتمد",
      "متابعة حالات الإرسال وتوثيق الأخطاء لتنفيذ المعالجة بسرعة",
    ],
    tasksEn: [
      "Extract invoice data and validate required fields",
      "Prepare UUID, XML and the approved integration workflow",
      "Track submissions and preserve actionable error records",
    ],
    impact: "أخطاء أقل ودورة فوترة أسرع ومسار واضح للمراجعة البشرية.",
    impactEn: "Fewer manual errors, faster invoicing cycles and a clear human review trail.",
    note: "مو كل فاتورة تحتاج اجتماع طوارئ.",
    noteEn: "Not every invoice deserves an emergency meeting.",
    accent: "#31e6b5",
  },
  {
    code: "B-02",
    slug: "barriz",
    name: "بَرِّز",
    nameEn: "BARRIZ",
    category: "الظهور المحلي ومنظومة Google",
    categoryEn: "Local Visibility & Google Ecosystem",
    role: "وكيل البحث المحلي وملف Google التجاري",
    roleEn: "Local SEO and Google Business Profile agent",
    quote: "خلّني أطلعك قدّام الناس الصح.",
    quoteEn: "Let me put you in front of the right local audience.",
    scenario:
      "النشاط ممتاز لكن بياناته متفرقة وظهوره المحلي ضعيف أو ملفه يحتاج تشخيصاً منظماً. بَرِّز يجمع الإشارات ويرتب الأولويات دون وعود وهمية بالترتيب أو الاستعادة.",
    scenarioEn:
      "The business is solid, but its local signals are fragmented or its profile needs structured diagnosis. BARRIZ organizes the evidence without promising rankings or platform decisions.",
    tasks: [
      "مراجعة اتساق الاسم والفئات والخدمات والبيانات المحلية",
      "تحليل نية البحث والفرص القريبة من العملاء الحقيقيين",
      "ترتيب أدلة حالات التحقق أو التعليق للمسارات الرسمية",
    ],
    tasksEn: [
      "Audit local business data, categories and service consistency",
      "Analyze local search intent and qualified discovery opportunities",
      "Organize verification or suspension evidence for official channels",
    ],
    impact: "حضور محلي أوضح وقرارات تحسين مبنية على بيانات قابلة للمراجعة.",
    impactEn: "Clearer local presence and evidence-based optimization decisions.",
    note: "العميل يدور عليك؛ نخلي الطريق أقصر.",
    noteEn: "Your customer is searching. Let us shorten the route.",
    accent: "#f4b66d",
  },
  {
    code: "B-03",
    slug: "rudd",
    name: "رُدّ",
    nameEn: "RUDD",
    category: "تجربة العميل العربية",
    categoryEn: "Arabic Customer Experience",
    role: "وكيل خدمة العملاء باللهجة والسياق السعودي",
    roleEn: "Saudi-context customer service agent",
    quote: "أفهم من أول «هلا»... وأرد بسرعة.",
    quoteEn: "I understand the first hala, then answer with context.",
    scenario:
      "تتكرر الأسئلة ويتأخر الرد بينما يريد العميل إجابة طبيعية لا تبدو آلية. رُدّ يفهم اللهجة والسياق ويربط المحادثة بأنظمة العمل، مع موافقة بشرية على القرارات الحساسة.",
    scenarioEn:
      "Questions repeat and responses slow down while customers expect a natural answer. RUDD understands local language and connects conversations to operations with approval gates for sensitive actions.",
    tasks: [
      "الإجابة من قاعدة معرفة معتمدة وبأسلوب عربي طبيعي",
      "الربط مع المتجر أو CRM لجلب حالة الطلب والمعلومات المسموحة",
      "تصعيد الحالات الحساسة للموظف مع ملخص واضح للمحادثة",
    ],
    tasksEn: [
      "Answer from an approved knowledge base in natural Arabic",
      "Connect with commerce or CRM systems for permitted order context",
      "Escalate sensitive cases with a concise conversation summary",
    ],
    impact: "رد أسرع وتجربة أقرب للعميل وعبء أقل على فريق الدعم.",
    impactEn: "Faster responses, more local relevance and less pressure on support teams.",
    note: "سريع، لكن ما يستعجل على حساب الثقة.",
    noteEn: "Fast, but never careless with trust.",
    accent: "#ff8f9d",
  },
  {
    code: "B-04",
    slug: "ammin",
    name: "أَمِّن",
    nameEn: "AMMIN",
    category: "الدفاع السيبراني والحوكمة",
    categoryEn: "Cyber Defense & Governance",
    role: "وكيل المراقبة الأمنية والاستعداد لضوابط NCA",
    roleEn: "Security monitoring and NCA readiness agent",
    quote: "ألاحظ الشيء الغريب قبل ما يصير خبر.",
    quoteEn: "I notice the unusual before it becomes the headline.",
    scenario:
      "الإشارات الأمنية كثيرة والفريق يحتاج ترتيباً سريعاً للحدث والأثر والإجراء. أَمِّن يربط التنبيهات بالسياق ويقترح الاستجابة داخل نطاق مصرح وتحت حوكمة واضحة.",
    scenarioEn:
      "Security signals are noisy and teams need fast context. AMMIN correlates events, explains impact and recommends authorized response steps under clear governance.",
    tasks: [
      "تجميع التنبيهات وربطها بالأصول والسلوك المعتاد",
      "ترتيب الحوادث بحسب الاحتمال والأثر والأولوية",
      "تجهيز سجل أدلة وتقارير تدعم الاستجابة وجاهزية الامتثال",
    ],
    tasksEn: [
      "Correlate alerts with assets and expected behavior",
      "Prioritize incidents by probability, impact and urgency",
      "Prepare evidence trails for response and compliance readiness",
    ],
    impact: "اكتشاف أسرع وضوضاء أقل وقرار أمني يمكن تفسيره ومراجعته.",
    impactEn: "Faster detection, less noise and security decisions that can be reviewed.",
    note: "هادئ... لأن الهلع ما عمره كان خطة استجابة.",
    noteEn: "Calm, because panic was never an incident response plan.",
    accent: "#00d4ff",
  },
  {
    code: "B-05",
    slug: "salni",
    name: "سَلْني",
    nameEn: "SALNI",
    category: "المعرفة المؤسسية وRAG",
    categoryEn: "Enterprise Knowledge & RAG",
    role: "وكيل البحث داخل وثائق الشركة مع المصادر",
    roleEn: "Source-grounded enterprise knowledge agent",
    quote: "اسألني... بس خلّ الإجابة من المصدر.",
    quoteEn: "Ask me anything relevant. I will keep the answer grounded.",
    scenario:
      "المعلومة موجودة لكنها ضائعة بين ملفات وسياسات وإصدارات متعددة. سَلْني يسترجع الإجابة من المصادر المصرح بها ويعرض مرجعها بدلاً من التخمين.",
    scenarioEn:
      "The answer exists, but it is buried across files, policies and versions. SALNI retrieves from approved sources and shows the reference instead of guessing.",
    tasks: [
      "فهرسة المستندات مع الصلاحيات والإصدارات ومصدر كل جزء",
      "البحث الدلالي وتوليد إجابات مرتبطة بمراجع قابلة للفتح",
      "رفض الإجابة أو طلب توضيح عندما لا يكفي المصدر المتاح",
    ],
    tasksEn: [
      "Index documents with permissions, versions and source lineage",
      "Run semantic retrieval and produce answers with usable citations",
      "Decline or ask for clarification when evidence is insufficient",
    ],
    impact: "وقت بحث أقل ومعرفة قابلة للحوكمة وثقة أعلى في الإجابات.",
    impactEn: "Less search time, governed knowledge and more trustworthy answers.",
    note: "يتفلسف؟ فقط إذا كانت الفلسفة موجودة في الملف.",
    noteEn: "It only gets philosophical when the document does.",
    accent: "#b88cff",
  },
  {
    code: "B-06",
    slug: "nammi",
    name: "نَمِّ",
    nameEn: "NAMMI",
    category: "الإعلانات والأداء التجاري",
    categoryEn: "Advertising & Commercial Performance",
    role: "وكيل تحسين الحملات والعائد على الإنفاق الإعلاني",
    roleEn: "Campaign optimization and ROAS agent",
    quote: "أقلّل الغلط... وأزوّد اللي يجيب نتيجة.",
    quoteEn: "Spend less on noise and more on what proves value.",
    scenario:
      "تتحرك الميزانية بين الحملات بينما يصعب ربط النقر بالعميل والقيمة. نَمِّ يجمع بيانات التحويل ويقترح قرارات اختبار وتوزيع يمكن قياس أثرها قبل التوسع.",
    scenarioEn:
      "Budgets move while clicks remain disconnected from qualified customers and value. NAMMI connects conversion data to testable allocation decisions before scale.",
    tasks: [
      "ربط القنوات ببيانات التحويل وجودة العميل لا بعدد النقرات فقط",
      "اقتراح تجارب للرسائل والجمهور وصفحات الهبوط",
      "توجيه الميزانية وفق قواعد وحدود وموافقات محددة مسبقاً",
    ],
    tasksEn: [
      "Connect channels to conversion quality, not clicks alone",
      "Propose structured message, audience and landing-page tests",
      "Recommend budget moves within predefined limits and approvals",
    ],
    impact: "إنفاق أذكى وقرارات أسرع وصورة أوضح لتكلفة النمو الحقيقي.",
    impactEn: "Smarter spend, quicker decisions and a clearer view of growth cost.",
    note: "عنده حساسية مزمنة من الميزانية الضايعة.",
    noteEn: "It has a healthy allergy to wasted budget.",
    accent: "#ff875e",
  },
  {
    code: "B-07",
    slug: "anjiz",
    name: "أَنْجِز",
    nameEn: "ANJIZ",
    category: "المشاريع والعمليات",
    categoryEn: "Projects & Operations",
    role: "وكيل PMO للتقدم والمخاطر والإنذار المبكر",
    roleEn: "PMO progress, risk and early-warning agent",
    quote: "المشروع يحتاج وضوح... مو ركض أكثر.",
    quoteEn: "The project needs clarity, not more running around.",
    scenario:
      "المهام موزعة والتقارير تتأخر والمخاطر لا تظهر إلا عند الموعد النهائي. أَنْجِز يجمع الإشارات من PMO وERP ويحولها إلى متابعة مفهومة وقابلة للتنفيذ.",
    scenarioEn:
      "Tasks are scattered, reports arrive late and risks surface near deadlines. ANJIZ turns PMO and ERP signals into clear, actionable follow-up.",
    tasks: [
      "تجميع تقدم الجداول والاعتماديات والميزانية في صورة واحدة",
      "اكتشاف مؤشرات التأخير والاختناق قبل تفاقمها",
      "توليد موجز تنفيذي يحدد القرار والمسؤول والموعد التالي",
    ],
    tasksEn: [
      "Combine schedule, dependency and budget progress",
      "Detect delay and bottleneck signals before escalation",
      "Generate executive briefs with owner, decision and next date",
    ],
    impact: "مفاجآت أقل وتنسيق أوضح ووقت أكبر للعمل بدل مطاردة التحديثات.",
    impactEn: "Fewer surprises, clearer ownership and less time chasing updates.",
    note: "يحب الجدول... لكنه يحب الإنجاز أكثر.",
    noteEn: "It likes the schedule, but it likes delivery more.",
    accent: "#58b8ff",
  },
  {
    code: "B-08",
    slug: "thabbit",
    name: "ثَبِّت",
    nameEn: "THABBIT",
    category: "السحابة واستمرارية الخدمة",
    categoryEn: "Cloud & Service Continuity",
    role: "وكيل المراقبة والتوسع التلقائي وكفاءة التكلفة",
    roleEn: "Cloud reliability, autoscaling and cost-efficiency agent",
    quote: "الضغط يرتفع؟ أوسّع بهدوء.",
    quoteEn: "Traffic climbs? I scale without the drama.",
    scenario:
      "ترتفع الزيارات أو تتغير الأحمال بينما يحتاج المنتج إلى استقرار وتكلفة منضبطة. ثَبِّت يراقب الموارد ويشغّل إجراءات محسوبة مع مسار رجوع واضح.",
    scenarioEn:
      "Traffic and workloads change while the product needs stable service and controlled cost. THABBIT monitors resources and executes governed actions with rollback paths.",
    tasks: [
      "مراقبة مؤشرات الأداء والسعة والتنبيه قبل الوصول للحدود",
      "تشغيل قواعد التوسع أو خفض السعة ضمن سياسات معتمدة",
      "متابعة النسخ الاحتياطي والتكلفة والحوادث التشغيلية",
    ],
    tasksEn: [
      "Monitor capacity and performance before limits are reached",
      "Apply scaling policies within approved operational guardrails",
      "Track backups, cost signals and reliability incidents",
    ],
    impact: "استمرارية أعلى وتكلفة أوضح وقدرة على التوسع دون ارتباك.",
    impactEn: "Higher continuity, clearer cost and calmer scaling.",
    note: "شغله يبان غالباً لما ما يصير شيء.",
    noteEn: "Its best work is often when nothing goes wrong.",
    accent: "#91a8c7",
  },
  {
    code: "B-09",
    slug: "zawwid",
    name: "زَوِّد",
    nameEn: "ZAWWID",
    category: "المبيعات والتجارة الإلكترونية",
    categoryEn: "Sales & Commerce",
    role: "وكيل استعادة السلات والتوصيات والمبيعات المساندة",
    roleEn: "Cart recovery, recommendation and assisted-sales agent",
    quote: "السلة توقفت؟ أعطيها دفعة ذكية.",
    quoteEn: "A cart paused? I give it a relevant nudge.",
    scenario:
      "يتصفح العميل ويقارن ثم يغادر قبل إتمام الطلب. زَوِّد يقرأ الإشارة المسموحة ويختار متابعة مفيدة بالتوقيت والقناة المناسبين دون إزعاج أو خصم عشوائي.",
    scenarioEn:
      "Customers browse, compare and leave before checkout. ZAWWID uses permitted signals to choose a relevant follow-up without spam or random discounts.",
    tasks: [
      "رصد السلات المتروكة وتقسيمها بحسب القيمة والاحتمال",
      "تخصيص الرسالة أو التوصية وفق السلوك والموافقة التسويقية",
      "قياس الاسترداد والهامش وإيقاف الأساليب التي لا تضيف قيمة",
    ],
    tasksEn: [
      "Segment abandoned carts by value and recovery likelihood",
      "Personalize follow-up within consent and channel rules",
      "Measure recovered revenue and stop low-value tactics",
    ],
    impact: "تحويل أعلى وإيراد مستعاد وتجربة بيع أكثر احتراماً للعميل.",
    impactEn: "Higher conversion, recovered revenue and more respectful selling.",
    note: "يعرف متى يذكّر... ويعرف متى يسكت.",
    noteEn: "It knows when to remind and when to stop.",
    accent: "#55d6a5",
  },
  {
    code: "B-10",
    slug: "warrini",
    name: "وَرِّني",
    nameEn: "WARRINI",
    category: "البيانات والرؤية التنفيذية",
    categoryEn: "Data & Executive Intelligence",
    role: "وكيل التحليلات ولوحات القيادة والأسئلة باللغة الطبيعية",
    roleEn: "Executive analytics and natural-language BI agent",
    quote: "ورّني السؤال... وأرجّع لك القرار.",
    quoteEn: "Bring the question. I will return the decision context.",
    scenario:
      "البيانات موجودة لكن القرار موزع بين تقارير وجداول وتعريفات مختلفة للمؤشر نفسه. وَرِّني يوحّد السؤال والمصدر ويشرح ما تغيّر ولماذا يستحق الانتباه.",
    scenarioEn:
      "Data exists, but decisions are scattered across reports and conflicting metric definitions. WARRINI connects the question, source and change that deserves attention.",
    tasks: [
      "تحويل السؤال الطبيعي إلى استعلامات محكومة بالصلاحيات",
      "تجميع المؤشرات وبناء لوحات لحظية مع تعريف واضح لكل مقياس",
      "اكتشاف الانحرافات وتقديم تفسير قابل للتتبع إلى المصدر",
    ],
    tasksEn: [
      "Translate natural-language questions into permission-aware queries",
      "Build live dashboards with clear metric definitions",
      "Detect anomalies and trace explanations back to source data",
    ],
    impact: "وقت أقل في تجهيز التقرير ووقت أكبر لاتخاذ قرار مفهوم ومدعوم.",
    impactEn: "Less time preparing reports and more time making supported decisions.",
    note: "ما يحب الجداول الطويلة... إلا إذا كانت فعلاً تقول شيء.",
    noteEn: "It only respects a long spreadsheet when it says something useful.",
    accent: "#c776ff",
  },
];
