const pick=(en,ar,eng)=>en?eng:ar;
const chip=(text)=>`<span class="bx-chip">${text}</span>`;
export function modelVisual(id,step,en){
 const t=(ar,eng)=>pick(en,ar,eng);
 const title=t('مشروع فيلا · الرياض','Villa project · Riyadh');
 const mark='<span class="bx-person-initial" aria-hidden="true">M</span>';
 if(id==='rise')return `<div class="bx-ui bx-pipeline" data-visual-step="${step}"><div class="bx-ui-top"><strong>${t('مسار المبيعات','Sales pipeline')}</strong>${chip(t('مثال تفاعلي','Interactive example'))}</div><div class="bx-lanes">${[t('طلب جديد','New'),t('معاينة','Site visit'),t('عرض سعر','Proposal')].map((s,k)=>`<div class="bx-lane ${k===step?'is-current':''}"><header>${s}<b>${k===step?'1':'0'}</b></header>${k===step?`<article class="bx-deal">${mark}<strong>${title}</strong><p>${t('ترميم كامل · شمال الرياض','Full renovation · North Riyadh')}</p><span class="bx-deal-status">${[t('بانتظار التأهيل','Awaiting qualification'),t('الثلاثاء · 10:00 صباحًا','Tuesday · 10:00 AM'),t('العرض جاهز للمراجعة','Ready for review')][step]}</span><footer>${t('المسؤول: محمد','Owner: Mohamed')} <span>↗</span></footer></article>`:`<span class="bx-empty">${t('لا فرص في هذا المثال','No deals in this example')}</span>`}</div>`).join('')}</div><div class="bx-ui-note">${t('تتبّع انتقال الفرصة عبر المشاهد الثلاثة.','Follow the opportunity across the three scenes.')}</div></div>`;
 if(id==='pulse')return `<div class="bx-ui bx-command"><div class="bx-ui-top"><strong>${t('نبض الأعمال','Business pulse')}</strong>${chip(t('بيانات توضيحية','Sample data'))}</div><div class="bx-stat-grid"><div><small>${t('فرص نشطة','Active deals')}</small><strong>12</strong></div><div><small>${t('بانتظار اعتماد','Awaiting approval')}</small><strong>2</strong></div><div><small>${t('مصدر الإعلانات','Ads source')}</small><b>${t('غير متصل','Not connected')}</b></div></div><div class="bx-mini-chart"><span>${t('زمن أول رد · دقائق · مثال','First response · minutes · example')}</span><div class="bx-bars" role="img" aria-label="${t('أزمنة رد توضيحية: 8 و12 و10 و18 و24 دقيقة','Sample response times: 8, 12, 10, 18 and 24 minutes')}">${[8,12,10,18,24].map((v,k)=>`<div><b style="--bar-height:${v*3}px;--delay:${k*.1}s">${v}</b><small>${k+1}</small></div>`).join('')}</div></div><div class="bx-alert">${['◉','↗','✓'][step]} <span>${[t('٣ متابعات تحتاج انتباهك اليوم','3 follow-ups need your attention'),t('الرد أبطأ؛ راجع سجل توزيع الطلبات','Slower responses: review enquiry assignment'),t('قرار مقترح: إعادة توزيع الطلبات','Proposed decision: rebalance enquiries')][step]}</span></div></div>`;
 if(id==='scout')return `<div class="bx-ui bx-search"><div class="bx-ui-top"><strong>SCOUT / ${['DISCOVER','FIX QUEUE','REVIEW'][step]}</strong>${chip(t('مثال','Demo'))}</div><div class="bx-search-field"><span aria-hidden="true">⌕</span>${t('تكلفة ترميم فيلا بالرياض','Villa renovation cost in Riyadh')}</div><div class="bx-search-result"><small dir="ltr">example.com / renovation</small><strong>${t('خدمات ترميم الفلل — نطاق واضح وخطوات تنفيذ','Villa renovation — scope and delivery steps')}</strong><p>${t('فرصة لتوضيح التكلفة، المعاينة وطريقة إعداد عرض السعر.','An opportunity to explain costs, site visits and proposals.')}</p></div><div class="bx-fix-list">${[t('مراجعة الرابط الأساسي','Review canonical URL'),t('تصحيح الرابط الداخلي','Fix internal link'),t('تحديث وصف الخدمة','Update service description')].map((x,k)=>`<div><span class="${step===2?'bx-good':''}">${step===2?'✓':'◌'}</span><strong>${x}</strong><small>${step===2?t('جاهز للمراجعة','Ready to review'):t('مقترح','Suggested')}</small></div>`).join('')}</div></div>`;
 if(id==='echo')return `<div class="bx-ui bx-chat"><div class="bx-ui-top"><strong>${t('محادثة عميل','Customer conversation')}</strong>${chip(t('سيناريو توضيحي','Example scenario'))}</div><div class="bx-bubble bx-in">${t('هل تنفذون ترميم فلل؟','Do you renovate villas?')}</div><div class="bx-bubble bx-out"><img src="/assets/media/bowdy-presenter-small.webp" width="32" height="32" loading="lazy" alt="">${t('نعم، ما موقع المشروع ونطاق العمل المطلوب؟','Yes. Where is the project and what work is needed?')}</div>${step>0?`<div class="bx-bubble bx-in">${t('شمال الرياض، ترميم كامل.','North Riyadh, full renovation.')}</div><div class="bx-extracted">${chip(t('ترميم كامل','Full renovation'))}${chip(t('شمال الرياض','North Riyadh'))}</div>`:`<span class="bx-typing" aria-label="${t('عرض حركة الكتابة','Typing animation')}"><i></i><i></i><i></i></span>`}${step===2?`<div class="bx-alert">✓ ${t('ملخص جاهز للموظف · اقتراح معاينة','Summary ready for the team · propose a visit')}</div>`:''}</div>`;
 if(id==='relay')return `<div class="bx-ui bx-workflow"><div class="bx-ui-top"><strong>${t('مسار المعاينة','Site-visit workflow')}</strong>${chip(['DESIGN','PREVIEW','REVIEW'][step])}</div><div class="bx-flow">${[t('طلب مؤهل','Qualified enquiry'),t('توزيع حسب المنطقة','Assign by area'),t('إنشاء مهمة','Create task'),t('موافقة الإرسال','Approve message')].map((x,k)=>`<div class="bx-flow-node ${k<=step?'bx-complete':''}" style="--delay:${k*.13}s"><span>${k<=step?'✓':String(k+1).padStart(2,'0')}</span><strong>${x}</strong><small>${k<=step?t('محاكاة مكتملة','Simulation complete'):t('بانتظار الخطوة السابقة','Awaiting previous step')}</small></div>`).join('')}</div><p class="bx-ui-note">${t('محاكاة بصرية؛ لا تُرسل رسائل ولا تتغير بيانات فعلية.','Visual simulation; no messages are sent and no live records change.')}</p></div>`;
 return `<div class="bx-ui bx-foundation"><div class="bx-ui-top"><strong>BOWDY WORKSPACE</strong>${chip(t('بيئة توضيحية','Demo workspace'))}</div><div class="bx-core-brand"><img src="/assets/brand/bowdy-labs-mark.svg" width="54" height="54" alt=""><div><strong>${t('مساحة عمل الشركة','Company workspace')}</strong><small>ONE IDENTITY · SHARED FOUNDATION</small></div></div><div class="bx-permissions">${[t('مدير الشركة','Company owner'),t('مدير المبيعات','Sales manager'),t('موظف الخدمة','Service staff')].map((x,k)=>`<div class="${step===k?'is-current':''}">${mark}<span>${x}</span><b>${[t('إدارة واعتماد','Manage & approve'),t('مبيعات وتقارير','Sales & reports'),t('طلبات ومحادثات','Enquiries & conversations')][k]}</b></div>`).join('')}</div><div class="bx-alert">✓ ${[t('دخول واحد للمنتجات المتاحة','One login for enabled products'),t('المعرفة تظهر وفق الصلاحية','Knowledge access follows permissions'),t('كل اعتماد محفوظ في سجل الأثر','Every approval has an action record')][step]}</div></div>`;
}
